# Generated by Django 2.2.6 on 2019-10-08 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('hotel_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=120)),
                ('star_rating', models.IntegerField()),
                ('address', models.CharField(max_length=120)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_number', models.IntegerField()),
                ('room_type', models.CharField(max_length=60)),
                ('type', models.CharField(max_length=120)),
                ('beds', models.IntegerField()),
                ('max_occupancy', models.IntegerField()),
                ('cost_per_night', models.IntegerField()),
                ('hotel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HotelsAppCRUD.Hotel')),
            ],
        ),
        migrations.CreateModel(
            name='RoomService',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_description', models.CharField(max_length=120)),
                ('service_price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='RoomReservation',
            fields=[
                ('reservation_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_number', models.CharField(max_length=120)),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField()),
                ('hotel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HotelsAppCRUD.Hotel')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HotelsAppCRUD.Room')),
            ],
        ),
        migrations.CreateModel(
            name='RoomCharges',
            fields=[
                ('room_charge_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_invoice', models.DecimalField(decimal_places=2, max_digits=5)),
                ('reservation_id',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HotelsAppCRUD.RoomReservation')),
                ('service_id',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HotelsAppCRUD.RoomService')),
            ],
        ),
    ]
