# Generated by Django 2.2.6 on 2019-10-18 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('credit_card_no', models.CharField(max_length=100)),
                ('phone_number', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('hotel_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=120)),
                ('star_rating', models.IntegerField()),
                ('address1', models.CharField(max_length=120)),
                ('address2', models.CharField(max_length=120)),
                ('county', models.CharField(max_length=120)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=120)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_number', models.IntegerField()),
                ('room_type', models.CharField(choices=[('D', 'Double Deluxe Room'), ('S', 'Single Deluxe Room'), ('H', 'Honey Moon Suite'), ('E', 'Economy Double')], default='Economy Double', max_length=60)),
                ('type', models.CharField(choices=[('P', 'Package Deal'), ('O', 'One Time Reservation'), ('M', 'Membership Deal'), ('C', 'Concierge Reservation')], default='One Time Reservation', max_length=120)),
                ('beds', models.IntegerField()),
                ('max_occupancy', models.IntegerField()),
                ('cost_per_night', models.IntegerField()),
                ('hotel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HotelsAppCRUD.Hotel')),
            ],
        ),
        migrations.CreateModel(
            name='RoomService',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_description', models.CharField(max_length=120)),
                ('service_price', models.DecimalField(decimal_places=2, default='', max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='RoomReservation',
            fields=[
                ('reservation_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_number', models.CharField(max_length=120)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('number_of_adults', models.IntegerField()),
                ('number_of_children', models.IntegerField()),
                ('payment_no', models.CharField(max_length=120)),
                ('customer_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='HotelsAppCRUD.Customer')),
                ('hotel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HotelsAppCRUD.Hotel')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HotelsAppCRUD.Room')),
            ],
        ),
        migrations.CreateModel(
            name='RoomCharges',
            fields=[
                ('room_charge_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(default='', max_length=120)),
                ('discount_code', models.CharField(default='', max_length=20)),
                ('discount_price', models.DecimalField(decimal_places=2, default='', max_digits=5)),
                ('reservation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HotelsAppCRUD.RoomReservation')),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HotelsAppCRUD.RoomService')),
            ],
        ),
        migrations.CreateModel(
            name='RoomBilling',
            fields=[
                ('reservation_id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_no', models.CharField(default='', max_length=120)),
                ('billing_address1', models.CharField(max_length=120)),
                ('billing_address2', models.CharField(max_length=120)),
                ('county', models.CharField(max_length=120)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=120)),
                ('total_discounts', models.DecimalField(decimal_places=2, default='', max_digits=5)),
                ('total_invoice', models.DecimalField(decimal_places=2, default='', max_digits=5)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HotelsAppCRUD.Customer')),
                ('room_charge_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HotelsAppCRUD.RoomCharges')),
            ],
        ),
    ]
