# Generated by Django 2.2.6 on 2019-10-22 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelsAppCRUD', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('D', 'Double Deluxe Room'), ('S', 'Single Deluxe Room'), ('H', 'Honey Moon Suite'), ('E', 'Economy Double')], default='E', max_length=60),
        ),
        migrations.AlterField(
            model_name='room',
            name='type',
            field=models.CharField(choices=[('P', 'Package Deal'), ('O', 'One Time Reservation'), ('M', 'Membership Deal'), ('C', 'Concierge Reservation')], default='O', max_length=120),
        ),
    ]
