# Generated by Django 2.2.6 on 2019-10-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelsAppCRUD', '0002_auto_20191022_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='credit_card_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='address2',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='latitude',
            field=models.DecimalField(decimal_places=7, max_digits=9),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='longitude',
            field=models.DecimalField(decimal_places=7, max_digits=9),
        ),
        migrations.AlterField(
            model_name='room',
            name='cost_per_night',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='roombilling',
            name='billing_address2',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='roomcharges',
            name='discount_code',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='roomreservation',
            name='payment_no',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
