# Generated by Django 2.2.6 on 2019-10-16 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelsAppCRUD', '0002_customer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomreservation',
            name='from_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='roomreservation',
            name='to_date',
            field=models.DateField(),
        ),
    ]
