# Generated by Django 2.2.6 on 2019-10-26 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelsAppCRUD', '0003_auto_20191024_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='cost_per_night',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
