# Generated by Django 2.2.6 on 2019-11-19 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelsAppCRUD', '0005_remove_roomreservation_room_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='hotel_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_hotel', to='HotelsAppCRUD.Hotel'),
        ),
        migrations.AlterField(
            model_name='roombilling',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_customer', to='HotelsAppCRUD.Customer'),
        ),
        migrations.AlterField(
            model_name='roombilling',
            name='room_charge_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_charge', to='HotelsAppCRUD.RoomCharges'),
        ),
        migrations.AlterField(
            model_name='roomcharges',
            name='reservation_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charge_reservation', to='HotelsAppCRUD.RoomReservation'),
        ),
        migrations.AlterField(
            model_name='roomcharges',
            name='service_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charge_service', to='HotelsAppCRUD.RoomService'),
        ),
        migrations.AlterField(
            model_name='roomreservation',
            name='customer_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='reservation_customer', to='HotelsAppCRUD.Customer'),
        ),
        migrations.AlterField(
            model_name='roomreservation',
            name='hotel_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_hotel', to='HotelsAppCRUD.Hotel'),
        ),
        migrations.AlterField(
            model_name='roomreservation',
            name='room_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_room', to='HotelsAppCRUD.Room'),
        ),
    ]
