# Generated by Django 2.2.6 on 2019-11-20 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelsAppCRUD', '0006_auto_20191119_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomreservation',
            name='reservation_description',
            field=models.CharField(default='', max_length=60),
        ),
    ]
