# Generated by Django 2.2.6 on 2019-12-04 19:44

import djongo.models.fields
from django.db import migrations, models

import HotelsAppCRUD.models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelsAppCRUD', '0007_roomreservation_reservation_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomReservationView',
            fields=[
                ('reservation_id', models.AutoField(primary_key=True, serialize=False)),
                ('reservation_description', models.CharField(max_length=60)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('number_of_adults', models.IntegerField()),
                ('number_of_children', models.IntegerField()),
                ('payment_no', models.CharField(blank=True, max_length=120, null=True)),
                ('hotel', djongo.models.fields.ArrayModelField(model_container=HotelsAppCRUD.models.Hotel)),
                ('customer', djongo.models.fields.ArrayModelField(model_container=HotelsAppCRUD.models.Customer)),
                ('room', djongo.models.fields.ArrayModelField(model_container=HotelsAppCRUD.models.Room)),
            ],
            options={
                'db_table': 'HotelsAppCRUD_roomreservation_view',
                'managed': False,
            },
        ),
    ]
